### ISSUE TITLE
Add Trait Support

### ISSUE THREAD

**Issue by iamazik** [Naoray/laravel-package-maker#30]
Any plan to add a trait command support where the command will add traits inside the trait folder?

**Comment by Naoray** [comment]
@iamazik could u explain what u mean by that on an example?

**Comment by iamazik** [comment]
I just simply want to run `php artisan package:trait MyTrait` command and that will create a `MyTrait` inside the `src/Traits` folder with the following stub:

```php
<?php

namespace Vendor\Package\Traits;

trait MyTrait
{
    //
}
```

**Comment by Naoray** [comment]
@iamazik ah ok. Sure can do this.

You can create a PR for it or wait for @rennokki or me to implement it :)

**Comment by Naoray** [comment]
@iamazik added `package:trait` command in v1.2.5

**Comment by iamazik** [comment]
@Naoray Nice, don't forget to also add support for views :)

**Comment by Naoray** [comment]
@iamazik I don't think we need support for creating views. It's like config files... you only need to create a file and you are done.

**Comment by iamazik** [comment]
Right, the confusion I always had is where to put it. So, I think it would be helpful for fresher and they won't have to this confusion again. Not sure if I was the only one with this confusion.

**Comment by Naoray** [comment]
Under `resources/views`. Try the `package:notifocation -m test` and u ll
see where the view ll be created
