### ISSUE TITLE
Add support for Laravel 6.0

### ISSUE THREAD

**Issue by Naoray** [Naoray/laravel-package-maker#54]
* [ ] Go through the [upgrade guide](https://laravel.com/docs/6.0/upgrade) and change everything as suggested
* [ ] Make sure all tests are passing afterwards

**Comment by immeyti** [comment]
May I start working on this?

**Comment by Naoray** [comment]
Sure, give it a try. :)

**Comment by Naoray** [comment]
@immeyti how are you doing? Do you need help with this?

**Comment by immeyti** [comment]
I haven't started yet. I'll work on it tomorrow. I'll keep you posted.
Tnx for following up.

**Comment by Naoray** [comment]
Thanks for your contribution @immeyti !!!
