### ISSUE TITLE
Exhausted allowed memory on Model Creation

### ISSUE THREAD

**Issue by NT-andrewgosselin** [Naoray/laravel-package-maker#55]
I only ever encounter this error when running the "package:model Model --all" command, I have increased my php memory_limit to 2 gigabytes which should be enough to run the migration and seed commands but I encountered the same error.

"$ php artisan package:model Models/User --all
Model created successfully.
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 270336 bytes) in /media/newtech/8AEC-C56F/Newtech/Development/Projects/package-factory/vendor/laravel/framework/src/Illuminate/Console/GeneratorCommand.php on line 97"

I am running Ubuntu 18.0.4 if that helps.
I have never encountered this error other than with using this package.

**Comment by Naoray** [comment]
Thanks for the report! Got it fixed.
