### ISSUE TITLE
Make it configurable

### ISSUE THREAD

**Issue by bernhardh** [Naoray/laravel-package-maker#63]
It would be great, to add a config file, so we can define some defaults. I don't want to add package-path, author, email, copyright, CI, etc. all the time.

**Comment by Naoray** [comment]
Do you mean when you create a package or when you execute single commands from this package?

**Comment by bernhardh** [comment]
I mean when i create a package. It would be just a good idea, that I don't have to repeat myself on every `php artisan make:package` command, since in most cases, just the first question will get a different answer on all packages.

**Comment by Naoray** [comment]
OK. I am not creating that many packages in a row. So, that's not an issue for me. If you however have an issue with it I'd accept a PR which introduces this kind of configuration.

**Comment by Arcesilas** [comment]
Hi,

By default, Composer (when running `composer init`) uses the git global `github.user` configuration value, which can be defined with:
```
git config --global github.user "John Doe"
```
This will be the default value for the vendor name when prompting.

It could be interesting to have the same behaviour (it would also be consistent).

**Comment by Naoray** [comment]
I am open to PRs for this
