### ISSUE TITLE
7.x 8.x support?

### ISSUE THREAD

**Issue by 1e4** [Naoray/laravel-package-maker#65]
Just upgrading to 7.x and the package is relying on 6.0 components of Laravel, is there intentions to support this for 7 and 8?

**Comment by Naoray** [comment]
I am open for PRs :)

**Comment by 1e4** [comment]
I'm looking at how to upgrade, I upgraded the `composer.json` to 7.x but I'm getting an error thrown and have no idea how to go about it

```
> post-autoload-dump: @php artisan package:discover --ansi
Executing command (CWD): '/usr/bin/php7.4' -d allow_url_fopen='1' -d disable_functions='' -d memory_limit='-1' artisan package:discover --ansi

   Illuminate\Contracts\Container\BindingResolutionException 

  Unresolvable dependency resolving [Parameter #1 [ <required> $customStubPath ]] in class Illuminate\Database\Migrations\MigrationCreator

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:1026
    1022|     protected function unresolvablePrimitive(ReflectionParameter $parameter)
    1023|     {
    1024|         $message = "Unresolvable dependency resolving [$parameter] in class {$parameter->getDeclaringClass()->getName()}";
    1025| 
  > 1026|         throw new BindingResolutionException($message);
    1027|     }
    1028| 
    1029|     /**
    1030|      * Register a new resolving callback.

      +21 vendor frames 
  22  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

I checked the upgrade guide but couldn't find anythign

**Comment by Naoray** [comment]
I added the necessary changes to resolve this issue in the [`prepare-upgrade`](https://github.com/Naoray/laravel-package-maker/tree/prepare-upgrade) branch. Haven't checked the [upgrade guide](https://laravel.com/docs/7.x/upgrade) if we have to change other things though.

**Comment by 1e4** [comment]
Branch seems to be working, will keep you posted for any bugs thank you very much :+1:

**Comment by Naoray** [comment]
You are welcome. If you don't encounter bugs let me know, otherwise I ll merge it next week and release a new version

**Comment by 1e4** [comment]
Thank you very much. And yep will keep you posted
